title: Duskwave Studios
baseURL: "https://aurainsignia.github.io/ds-blog/"
copyright: "© Duskwave Studios"
theme: papermod
languageCode: en-us
#relativeURLs: true
canonifyURLs: true

params:
  defaultTheme: auto # to switch between dark or light according to browser theme
  homeInfoParams:
    Title: The Dead Reckoning Development Blog
    Content: Welcome to the Dead Reckoning development blog!

  socialIcons:
    - name: "Discord"
      url: "https://discord.gg/MrP5nTvjC3"

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    # limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: [ "title", "permalink", "summary", "content" ]

menu:
  main:
    - identifier: search
      name: Search
      url: search/
      weight: 10
    - identifier: archives
      name: Archive
      url: archives/
      weight: 20

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search